In [1]:
from utils.read_jsonl import read_jsonl
from transformers import BertTokenizer, DistilBertTokenizer
from collections import Counter
import pandas as pd

In [2]:
df_train = read_jsonl("DB-bio/combined_train_and_train_sft_anonymized.jsonl")
df_val = read_jsonl("DB-bio/combined_val_and_val_sft_anonymized.jsonl")
df_combined = pd.concat((df_train, df_val), axis=0, ignore_index=True)
len(df_combined)

4362

In [3]:
df_anonymized = df_combined[df_combined["label"] == 1]
df_not_anonymized = df_combined[df_combined["label"] == 0]
len(df_anonymized), len(df_not_anonymized), len(df_anonymized) + len(df_not_anonymized)

(2181, 2181, 4362)

In [4]:
tokenizer_distilbert = DistilBertTokenizer.from_pretrained("distilbert-base-uncased") 
tokenizer_bert = BertTokenizer.from_pretrained("bert-base-uncased")

In [5]:
def tokenize(row, tok):
    ids = tok(row["text"], padding="max_length", truncation=True, max_length=512)["input_ids"]
    counter_dict = Counter(ids)
    return counter_dict

In [6]:
df_anonymized_counts = df_anonymized.apply(lambda row: tokenize(row, tokenizer_bert), axis=1)
df_not_anonymized_counts = df_not_anonymized.apply(lambda row: tokenize(row, tokenizer_bert), axis=1)

In [7]:
df_anonymized_counts_agg = df_anonymized_counts.sum()
df_not_anonymized_counts_agg = df_not_anonymized_counts.sum()

In [8]:
df_anonymized_tokens_sorted =  sorted(list(df_anonymized_counts_agg.items()), key=lambda x: x[1], reverse=True)
df_not_anonymized_tokens_sorted =  sorted(list(df_not_anonymized_counts_agg.items()), key=lambda x: x[1], reverse=True)
len(df_anonymized_tokens_sorted), len(df_not_anonymized_tokens_sorted)

(13453, 20382)

In [9]:
[(df_anonymized_tokens_sorted[500][1], df_not_anonymized_tokens_sorted[500][1]),
 (df_anonymized_tokens_sorted[1000][1], df_not_anonymized_tokens_sorted[1000][1]),
 (df_anonymized_tokens_sorted[3000][1], df_not_anonymized_tokens_sorted[3000][1])]

[(122, 160), (55, 83), (12, 25)]

In [10]:
all_keys = set(df_anonymized_counts_agg) | set(df_not_anonymized_counts_agg)
comparison = pd.DataFrame(
    [(tokenizer_bert.decode([key]), key, df_not_anonymized_counts_agg.get(key, 0), df_anonymized_counts_agg.get(key, 0)) for key in all_keys],
    columns=['token', 'token_id','original_count', 'anonymized_count']
)
comparison['diff'] = comparison['anonymized_count'] - comparison['original_count']

In [11]:
removed_tokens = comparison.sort_values(by='diff').head(1000)
removed_tokens

     token  token_id  original_count  anonymized_count   diff
130     he      2002           11595                23 -11572
15       ,      1010           32280             23933  -8347
138    his      2010            6282                28  -6254
126    and      1998           15926             12232  -3694
36       \      1032            3639                 0  -3639
...    ...       ...             ...               ...    ...
2121   com      4012             106                69    -37
2890  aged      4793              46                 9    -37
7008  ##wi      9148              38                 1    -37
4867  1887      6837              41                 4    -37
8909    wa     11333              38                 1    -37

[1000 rows x 5 columns]

In [12]:
new_tokens = comparison.sort_values(by='diff', ascending=False).head(1000)
new_tokens

            token  token_id  original_count  anonymized_count   diff
0           [PAD]         0          442136            512556  70420
40              a      1037           11129             39388  28259
151          this      2023             565             12776  12211
838        person      2711              46             11036  10990
165         their      2037             355              7934   7579
...           ...       ...             ...               ...    ...
4108     policies      6043               1                 9      8
2252    conducted      4146              15                23      8
7387   performers      9567               8                16      8
10246  automotive     12945              11                19      8
2233        types      4127               7                15      8

[1000 rows x 5 columns]

In [13]:
removed_tokens.to_csv("DB-bio/global_analysis_removed_tokens_top_1K.csv", index=False)
new_tokens.to_csv("DB-bio/global_analysis_added_tokens_top_1K.csv", index=False)

In [189]:
tokenizer_bert.decode(list(removed_tokens["token_id"] > ))

'he, his and \\. ( ) was " she the – hers n worldaoe - 1 new himi to st is den marcht york 3 as of three 2 4 americanl john julyer january juney april 2008 may 6 september first august 2012 2010 november 2007 won october\'2009 2013 5 four 2011 at san 2006r k has february 7 co december d sc son 2015 2014 8 all 10 five 2005 / w ’ 12 2004 s : grandon &k la britishmen no 11z or 2002 ko 15 13an open b 16u 2003 9 2000 london father 20es georged six 14 james 17 g c william bo 2001 o chicago 1996in 1998 ga 18v l f washington war brother 22 championships red 1978 1986 1997 cup 21 m 1999 manh 24c prix 1992 e jman be 1974 2016 france i philadelphia 1972 davidg men mo 1969 30 1985 cr t 1994 ma dr al 1963 seven ha wife thomas 19 1993 1989 1970 1976le south 1977 secondel 1995 1988ton 1964 ka los 29 ve hois 25 1980 1991 1990 go 27 best 1984 paulna french 1968 paris mu 1982 26ianone ; br angeles 1983ov 1975 robert 28 eight se 1981 1967 charles himself 1962 australian park 1987 royal old sa german z michael le 1965 1979 carolina thirdra 1971 called 1966to mc only ohio van 23 gr gold white 1960us 1959 jones became 000 pennsylvaniaey boston ke louis californialy 1961 1973 du so king 1951 champion us jrco olympicsie 1954re hi 1946 joseph english roka 1958 sovietro republican henry ufc went frank times 1956 fr whichf sirville tour womench championship r games daughter di 1947 1955 up ne bill nba hallers japan feki 0 college martin 1948 greatque 1953 sox bu 1952x fa hli both star 1938 lu ba when iitase del bobioriur massachusetts canada toronto canadian peter fourth england na indiaas air blackth 1957 who 31 nine smith santason 1945 betweenj williamster gidote germany formula 1935 house 1950 franciscoic 1939 vi doleyda $ wisconsin li 1936 dan el hill 1937 lo mexico pan8 1942 kup lee ri p2 1934 chi chinesealler po ra silver summer alsoner china florida vo winning wimbledon albert most indian 1930 cha kong twobni1 jo bi then ar hong richard va australia jersey 1931 ge marrs 1943loca edward greenko tom out ci iowa singlesian russian good ya 1941 mega school alexander madear des superut 1949 1940w ten pet nasang gu 1933or mi playedff wo cincinnatick rome pe people da re director time kentuckyhamke big ce brothers it 1932ini such unionden un but back davis fu4 generalva pro singapore 1926ry 1928 19246 et britain left per con ti berlin doubles rock armyker 1911 ken republic win3 west johnson blue derbytiil cooper mariaumbobe 1927 queenwell u von 1920 mary ni pahi 1923 wood0 moscow engineers usabergmall greatest olympicam taylor cross 1921 museum 1944ha now 500ba illinois yang ever bronze ag salmo medalgo chen italianls president japanese ambassador soyuz ben jean wila pat5 ai 1929 femaleøostt 1925 1918 ze arthur mer 1900 pre mark ki baltimore virginia civilev detroit harvard spanish jacksen en canir jan mooreak tu tar7 allen roundolo ireland brown mcc chris twice bbcceder 1919 wangrin mr democratic michigan roaday montreal # iron fl wei slamac brooklynks anthony ”hl jose 1917 scott fame pl atlanta stsit milan maryland hollywood bart beijing post fi would came 100 than kennedy “ vienna sixth winner long cleveland giovanni through stars 50ub finished cal sun 1888ich 1916 more cho cubs joe womanchi fifth dodgers birmingham jimku bel portland mac carr ed cats diegoierea columbia spain za 1905 twenty ing ham yuoni sistersi minnesotaky ambu manchesterardrd little val 1914 awardedzelan vnautge ferrariebzi mountfield pu willgi princeton rusmo mag ac denver kelly9et kanskibury indiana inc walker gal jedi worked cl nl mill colorado 1913 table youde male moved heavyweight cap million yankees seventh 1898 si antonio jimmy ta 6th 2nd kansas belgium jiurilin te dutch overallburg miamiung gen eng seattle countyhe reds navy indianapolis sydney wayne mike hanswood democrat tr 1908ana thlu 1922 jaup giantsya sons golden 40 bar court hu fightingcheadber kg irish 1912 il far las anderson 1915 brazilian history since wu land bay 1901 don abchn nationsju miller marie ncaa pilot penn gregory like wrote km karatezahal jacksonneyger karlnt carl bulls ab tigers warren 1894 pi 3rd months er lost into hourslle ur melme congress alex 1896ny roseland lotus tor elizabeth stakes institute os sp smhoji 1907un melbourne right ray 1910 where mitby however dermer belgian force wilnd tri houston georgia giro tokyo oxfordhan books 1899ot chief fightah florence uci professorstjafordyntzher munich becomeion huntss es francis gracieshtti full 1897 opened eddie im myau offrt husband ross ch lake lightweight par chopin com agedwi 1887 wa'

In [190]:
tokenizer_bert.decode(list(new_tokens["key"]))

'[PAD] a this person their they in year individual city another date early team country major century an late were mid notable 20th several significant multiple from region event town national club prestigious number european various 2000s prominent international certain same period sports 19th player 1990s on 1970s known local them birth with state 1980s professional 1960s well league athlete decade death one have renowned institution top 2010s for 1950s following that figure regional organization born partner different during specific 1940s years other 1930s recognized capital home artist subsequent later company are part political states competitor role tournament competition military midwest global events conflict teams distinguished location parent numerous month horse child sibling historical sport position 1920s high field competitive martial member series few away area passed europe educational large education cycling architect opponent uk religious colleague racing within previous northeastern recent arts achieved medical involved era related party players group industry offspring cultural figures race small vehicle competitions baseball family leader leading spouse countries publication culinary higher secured work by hometown fashion 21st place among honored cities media decades asia career over newspaper nation individuals received themselves died including football initial racer relative venue participated 18th performance trainer recognition engineering body victories chess firm 1880s health facility entertainment ranking program advanced popular southeasterned contributions contributed united comedic particular its cyclist style competitors 1890s establishment agency artists designer tennis continent composer term securing shortly famous level consecutive multi basketball music across subsequently engaged discipline government coastal dedicated legislative middle network legal 1910s public height additionally weight substantial community official asian triumph been leadership unique respected dining project cooking established clubs acknowledged participant included 1870s these comedian focused academic photographer scientific young esteem institutions teammate key motorsport distinctive past southeast end painter healthcare sector title siblings achieving honor urban mentor range insects tier projects broadcaster victory pursued influential locations initiated [ contributing led roles 1860s latter art regions entity accolades numbered despite diverse category business initially match milestone musician engineer active heritage average ] technical exploration address television associated after manufacturer age amount skilled start broadcast service caribbean research focus brand 1850s 16th specialized expertise athletes due initiative residence visual some relocated combat scene impressive soccer traditional elite spanning duration featured conference northeast record competing earning name includes members nearby enterprise passing east financial completed honors unspecified contests model achievementsern opponents concluded specializing venture participating condition located select additional architecturalquin development 1900s predecessor moreover artistic illness include neighboring diplomatic activities variety tenure final expert parents monarch coach turn nickname youth premier historic profession district children performances production circuit study collection close efforts humorous authored highly focusing involving endeavors personal those composers celebrated journey achieve platform residential abroad issue publicationsperson space southern previously interest innovative north impact character competed descendant yet legislature strategic educator matches creating rank homeland embarked outlet around type governmental literaryony gained humor northwest faced originating occurred secondary species incident teacher ranked experienced orbital distance pieces organizations transitioned acclaimed couple participation neighborhood positions annual pianist success elements equipment issues experience craft performer background earlier span entertainer names broad placement musicians similar division aviation support eastern pioneering works rounds online populousive universities challenging disciplines domain thereafter establishments classical single featuring private activityzed subject pivotal hemisphere noted important traveler score senior beyond language continental tournaments challenges participants remarkable methods highlighted being advancing transportation significantly held continued set marking languages creative moniker setting categories sporting content indigenous strategy consistent races award areas experts practitioner dates unit acc clinched opposing engaging instructor skills approach maintained provided starting animaltri affected globally iconic rival streets sum batting leagues vehicles considerable structure seater serving piece communication adopted talent stable instrumental hold distinction environment degree contest spiritual outstanding enthusiast continents audio design televised victorious consistently tragic themed publisher towards pursuits programs racetrack officer extended format 1830s common construction territory governing societal collective residing completing lifestyle substance secure periods groups practices occasions internationally maintaining commentary collaborated scholarly minor teens status employed branch returning extensive larger conditions teammates brief wins 17th techniques often mentioned collegiate attire opportunity advancement marked separate retail showcased travel not contemporary endurance professionals literature painting appearances method margin maritime demise colleagues training candidate eater magazines severe diplomat involvement metropolitan losses concluding profile infrastructure material particularly hospitality nationality africa website peers innovation pioneer products developed representing site teachers addressing responsible skill acquired facilities reaching former owner movement satiricaldable frequently environmental periodicalframe affiliatedrent managed technique social tribute changes sole spanned serious photography modest structures joining transition enforcement forces specifically humanitarian kingdom injury coast grandpa creator contender attributed 1840s achievement crafted majority scholar garnered influence defensive lineage society america 1820s genre generalized descent shifted surpassed formal captured encountered influenced entities assumed narrative scientist before hundreds worldwide explorer linked broader timed manufacturing racehorse outcomes studies decisive lower emerging lead throughout animated marriage pitcher entrepreneur promotion claimed relocating audience enhance crucial comprehensive topics presence creation chosen surname learning towns southwestern referred biblical proficient relatives strong induction realm governance produced product suggested luxury ventures qualificationchild resulted retiring ancestor reside distinct relationship fellow advance defense insights terms expressed initiatives celestial themes rare portion endeavor advocating maintain overseeing succeeded twenties biological prior creations advocated congressman establishing resulting attained newspapers presently endorsed networks experiences upcoming peer procedure committed degrees loss spot advocate abbreviation change launched guidance mediterranean excellence distinctions handful partnership dealing welfare defeat presenter researcher improvement gender management versatile collaborator critical main comedy romantic injuries standing potential enhancing widely introduced societies participate discussions 1800s positive prepared affluent misconduct furthermore holiday without blending squad obtained publishing adult naturalist personalities safety occurrence central label digital panel venues journalist undertook tallyholder dynamics multitude depicting physician progressionship physical collaboration legacy apparatus characterized depiction levels materials lighter actors original contenders graduation rights titled domestic representative shift register ventured stores succumbed overseas capacity widespread texts contemporariesial penned exceptional strategiesular scandinavian property knowledge companion places oversight pseudonym compete symbolic ruling facing ceased detailed gland showcase economic items practiced preserved policies conducted performers automotive types'

In [178]:
df_common_tokens = df_anonymized_tokens.join(df_not_anonymized_tokens, how="inner", on="token", lsuffix="_anonym")

In [179]:
len(df_common_tokens)

2361

In [162]:
tokenizer_bert.decode([tup[0] for tup in df_anonymized_tokens_sorted[:50]])

"[PAD] a the in., of this and person to their they was for - with at an on as year's from team ( ) city is individual another major early by date [CLS] [SEP] country born were century one late also that mid national after first"

In [163]:
tokenizer_bert.decode([tup[0] for tup in df_not_anonymized_tokens_sorted[:50]])

'[PAD], the. in and of he a to was - his for ( ) as at\'with s on \\ is " from an by [CLS] [SEP] – borns also first she has one team after world won that new american her who career two which'

In [ ]:
len(df_anonymized_tokens_sorted), len(df_not_anonymized_tokens_sorted)

In [191]:
tokenizer_bert.decode([i for i in range(999, 1200)])

'! " # $ % &\'( ) * +, -. / 0 1 2 3 4 5 6 7 8 9 : ; < = >? @ [ \\ ] ^ _ ` a b c d e f g h i j k l m n o p q r s t u v w x y z { | } ~ ¡ ¢ £ ¤ ¥ ¦ § ¨ © ª « ¬ ® ° ± ² ³ ´ µ ¶ · ¹ º » ¼ ½ ¾ ¿ × ß æ ð ÷ ø þ đ ħ ı ł ŋ œ ƒ ɐ ɑ ɒ ɔ ɕ ə ɛ ɡ ɣ ɨ ɪ ɫ ɬ ɯ ɲ ɴ ɹ ɾ ʀ ʁ ʂ ʃ ʉ ʊ ʋ ʌ ʎ ʐ ʑ ʒ ʔ ʰ ʲ ʳ ʷ ʸ ʻ ʼ ʾ ʿ ˈ ː ˡ ˢ ˣ ˤ α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω а б в г д е ж з и к л м н о п р с т у ф'

In [194]:
tokenizer_bert.decode(1012)

'.'